### PR TITLE
Add containerization with docker

### PR DESCRIPTION
**Pull request by salquier**
Hi @inoda !

So I found your project yesterday on reddit and I wanted to try it out - as it mostly corresponds to what we are looking for with my wife.

As there is no docker support for now and the open pull request has some problems, I made my own version which I propose here.

I tried to make an lightweight image with official docker images based on alpine.

### CODE REVIEW

**Comment by inoda** [comment]
@luketainton or @filipeforattini - do one of y'all want to try this out?

**Comment by luketainton** [comment]
I'll take a look now :)

**Comment by luketainton** [comment]
@inoda - this works! Screenshot confirms the container started up:
Screenshot 2020-10-09 at 21 12 36

@salquier - thank you so much for this 👍

**Comment by salquier** [comment]
@luketainton You're welcome !

I didn't put it on the readme, but I use it in production mode behind a reverse proxy. I made the configuration with ansible but I can provide a docker-compiled version if you are interested.

**Comment by luketainton** [comment]
> @luketainton You're welcome !
> 
> I didn't put it on the readme, but I use it in production mode behind a reverse proxy. I made the configuration with ansible but I can provide a docker-compiled version if you are interested.

That would be great, thanks!

**Comment by inoda** [comment]
@luketainton Thank you so much for checking this and @salquier thank you so much for doing this! 🙏 

Merging it up now. @salquier if you're up for it, some additions to the install options/instructions in the readme would be much appreciated!

**Comment by luketainton** [comment]
I guess users can change that once they clone the repo from GitHub

**Pull request merged**
